# Generated by Django 5.0.6 on 2024-07-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_payment_payment_link_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_id',
            field=models.TextField(blank=True, null=True, verbose_name='id сессии'),
        ),
    ]
