# Generated by Django 5.0.6 on 2024-07-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_link',
            field=models.TextField(blank=True, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
